### ISSUE TITLE
Unable to sort comments

### ISSUE THREAD

**Issue by smasry** [zendesk/zendesk_api_client_rb#342] opened 2017-08-31 00:45 UTC
The comments endpoint ( GET /api/v2/tickets/{ticket_id}/comments.json ) allows a sort_order parameter `sort_order` 
The sort_order option does not seem to pass through to the url parameters. 
`ticket.comments(sort_order: 'asc')`

**Comment by yachtcaptain23** [comment] 2019-04-08 15:49
+1, would be good to add sort as part of the functionality. I tried passing in as part of the URI using `&sort_order=created_at` but the Zendesk API casts it to `%26sort_order=created_at` which doesn't work.

**Comment by ecoologic** [comment] 2022-02-03 22:50
This appears to be a duplicate of #459, which has been answered.

**Closed by ecoologic** 2022-02-03 22:50 UTC
