### ISSUE TITLE
Adding multiple comments to a ticket will ignore the private flag and add all future messages as public.

### ISSUE THREAD

**Issue by wayrunner** [zendesk/zendesk_api_client_rb#489] opened 2022-03-09 16:04 UTC
Steps to reproduce:
```
zendesk_ticket = Zendesk.client.tickets.find!(id: zendesk_id)
zendesk_ticket.update(:comment=>{ :body=>"Private message", :public=>false })
zendesk_ticket.save!

zendesk_ticket.update(:comment=>{ :body=>"Message that should be private but is public instead", :public=>false })
zendesk_ticket.save!
```

**Comment by codealchemy** [comment] 2022-10-10 21:29
@wayrunner I'm unable to reproduce this on the latest release given the steps you provided, is this still an issue?

<details>
<summary>Reproduction attempts</summary>

```ruby
> ZendeskAPI::VERSION
=> "1.38.0.rc1"
> client = ZendeskAPI::Client.new { ... }
> ticket = client.tickets.find(id: 227)
> ticket.update(comment: { body: 'Private message1', public: false })
> ticket.save! # Message shows as private on ticket
> ticket.update(comment: { body: 'Private message2', public: false })
> ticket.save! # Message shows as private on ticket
> ticket.update(comment: { body: 'Public message1', public: true })
> ticket.save! # Message shows as public on ticket
> ticket.update(comment: { body: 'Private message3', public: false })
> ticket.save! # Message shows as private on ticket
```

</details>

**Comment by ecoologic** [comment] 2023-04-05 01:31
Cannot reproduce either. Closing. Please feel free to get back in touch if this is still an issue.

**Closed by ecoologic** 2023-04-05 01:31 UTC
