### ISSUE TITLE
README is misleading in regards to API authentication ability

### ISSUE THREAD

**Issue by jakeonfire** [zendesk/zendesk_api_client_rb#356] opened 2017-11-30 23:23 UTC
it says after the client example:

  Note: This ZendeskAPI API client only supports basic authentication at the moment.

but it definitely works with (at least) API token auth as well.

**Comment by hkmaly** [comment] 2018-11-20 16:39
I think it's supposed to mean the oauth is not working ...

**Comment by nogates** [comment] 2019-12-12 02:34
I am gonna close this since the issue is quite old (sorry about not replying to this earlier) and the README has some information about how to use OAuth tokens as well.

**Closed by nogates** 2019-12-12 02:34 UTC
